"""Behavior tests for ``kmesh.logic.motif_split`` (T0020).

These tests verify the fixed ``motif_split_v1`` catalogue through the public
no-arg interface only.  They are independent oracles: the protocol's literal
per-set ID lists, the seven-row bucket table, the 9-cell containment matrix,
hand-written anchor witnesses, reconstructed-from-JSON witnesses for the full
directory, spies around the accepted dependency binding for call-count and
participation, injected cross-split and structural violations that must be
rejected, an isolated dependency stand-in to observe pass-through, injected
failure sentinels for exception propagation, and independent subprocess checks
for determinism and import isolation.

The tests do not import any planning probe, do not use the product's private
constructors to generate expected values, and do not import torch / yaml /
training or model modules.  All expected lists are literal protocol values, not
generated by the tested allocator or a shared prefix rule.
"""

from __future__ import annotations

import copy
import io
import json
import os
import subprocess
import sys
from itertools import product
from pathlib import Path

import pytest

from kmesh.logic.proof import ProofStep, verify_proof
from kmesh.logic.proof_count import count_canonical_proofs
from kmesh.logic.depth import minimum_proof_depth
from kmesh.logic.motif import canonical_motif_key
from kmesh.logic.types import Atom, Clause, LogicValidationError

import kmesh.logic.motif_split as mcs
import kmesh.logic.motif_candidates as mcp

_MAX_FACT_CHECKS = 100_000
_MAX_DERIVATIONS = 100_000
_MAX_PROOF_STEPS = 100_000
_MAX_ORIENTATIONS = 100_000

# ---------------------------------------------------------------------------
# Protocol literals (fixed lists / table / matrix from motif_split_v1).
# Per-set candidate lists are in directory order (two-letter roots then their
# four extensions, roots in the fixed per-set order).  _ALL_IDS is the T0019
# directory order (all 2-letters, then all 3-letters over C/I/J/T).
# ---------------------------------------------------------------------------
_TRAIN_IDS = [
    "CJ", "CT", "IC", "II", "JC", "JI", "TJ", "TT",
    "CJC", "CJI", "CJJ", "CJT",
    "CTC", "CTI", "CTJ", "CTT",
    "ICC", "ICI", "ICJ", "ICT",
    "IIC", "III", "IIJ", "IIT",
    "JCC", "JCI", "JCJ", "JCT",
    "JIC", "JII", "JIJ", "JIT",
    "TJC", "TJI", "TJJ", "TJT",
    "TTC", "TTI", "TTJ", "TTT",
]
_DEV_IDS = [
    "CC", "IJ", "JT", "TI",
    "CCC", "CCI", "CCJ", "CCT",
    "IJC", "IJI", "IJJ", "IJT",
    "JTC", "JTI", "JTJ", "JTT",
    "TIC", "TII", "TIJ", "TIT",
]
_TEST_IDS = [
    "CI", "IT", "JJ", "TC",
    "CIC", "CII", "CIJ", "CIT",
    "ITC", "ITI", "ITJ", "ITT",
    "JJC", "JJI", "JJJ", "JJT",
    "TCC", "TCI", "TCJ", "TCT",
]
_ALL_IDS = (
    ["".join(p) for p in product("CIJT", repeat=2)]
    + ["".join(p) for p in product("CIJT", repeat=3)]
)
# Cross-check the literals: every fixed ID belongs to exactly one set.
assert (set(_TRAIN_IDS) | set(_DEV_IDS) | set(_TEST_IDS)) == set(_ALL_IDS)
assert not (set(_TRAIN_IDS) & set(_DEV_IDS))
assert not (set(_TRAIN_IDS) & set(_TEST_IDS))
assert not (set(_DEV_IDS) & set(_TEST_IDS))

_TRAIN_BUCKETS = [
    {"depth": 2, "proof_steps": 3, "candidate_count": 2, "distinct_motif_count": 2},
    {"depth": 2, "proof_steps": 4, "candidate_count": 4, "distinct_motif_count": 4},
    {"depth": 2, "proof_steps": 5, "candidate_count": 2, "distinct_motif_count": 2},
    {"depth": 3, "proof_steps": 4, "candidate_count": 4, "distinct_motif_count": 4},
    {"depth": 3, "proof_steps": 5, "candidate_count": 12, "distinct_motif_count": 12},
    {"depth": 3, "proof_steps": 6, "candidate_count": 12, "distinct_motif_count": 12},
    {"depth": 3, "proof_steps": 7, "candidate_count": 4, "distinct_motif_count": 4},
]
_DEV_BUCKETS = [
    {"depth": 2, "proof_steps": 3, "candidate_count": 1, "distinct_motif_count": 1},
    {"depth": 2, "proof_steps": 4, "candidate_count": 2, "distinct_motif_count": 2},
    {"depth": 2, "proof_steps": 5, "candidate_count": 1, "distinct_motif_count": 1},
    {"depth": 3, "proof_steps": 4, "candidate_count": 2, "distinct_motif_count": 2},
    {"depth": 3, "proof_steps": 5, "candidate_count": 6, "distinct_motif_count": 6},
    {"depth": 3, "proof_steps": 6, "candidate_count": 6, "distinct_motif_count": 6},
    {"depth": 3, "proof_steps": 7, "candidate_count": 2, "distinct_motif_count": 2},
]
_TEST_BUCKETS = [
    {"depth": 2, "proof_steps": 3, "candidate_count": 1, "distinct_motif_count": 1},
    {"depth": 2, "proof_steps": 4, "candidate_count": 2, "distinct_motif_count": 2},
    {"depth": 2, "proof_steps": 5, "candidate_count": 1, "distinct_motif_count": 1},
    {"depth": 3, "proof_steps": 4, "candidate_count": 2, "distinct_motif_count": 2},
    {"depth": 3, "proof_steps": 5, "candidate_count": 6, "distinct_motif_count": 6},
    {"depth": 3, "proof_steps": 6, "candidate_count": 6, "distinct_motif_count": 6},
    {"depth": 3, "proof_steps": 7, "candidate_count": 2, "distinct_motif_count": 2},
]
_EXPECTED_MATRIX = [
    {"source_split": "train", "target_split": "train", "edge_count": 72},
    {"source_split": "train", "target_split": "dev_composition", "edge_count": 0},
    {"source_split": "train", "target_split": "test_composition", "edge_count": 0},
    {"source_split": "dev_composition", "target_split": "train", "edge_count": 0},
    {"source_split": "dev_composition", "target_split": "dev_composition", "edge_count": 36},
    {"source_split": "dev_composition", "target_split": "test_composition", "edge_count": 0},
    {"source_split": "test_composition", "target_split": "train", "edge_count": 0},
    {"source_split": "test_composition", "target_split": "dev_composition", "edge_count": 0},
    {"source_split": "test_composition", "target_split": "test_composition", "edge_count": 36},
]
_EXPECTED_SUMMARY = {
    "candidate_count": 80,
    "distinct_motif_count": 80,
    "containment_edges": 144,
    "proper_containment_edges": 64,
    "cross_split_edges": 0,
}
_TOP_CONSTANTS = {
    "schema_version": "motif_split_catalogue_v1",
    "split_protocol": "motif_split_v1",
    "research_protocol": "e0_v3",
    "candidate_family": "left_spine_ops_v1",
    "matching": "complete_rooted_support_subtree",
}
_EXPECTED_BUDGETS = {
    "max_fact_checks": 100_000,
    "max_derivations": 100_000,
    "max_proof_steps": 100_000,
    "max_orientations": 100_000,
}
_EXPECTED_ROOT_IDS = {
    "train": ["CJ", "CT", "IC", "II", "JC", "JI", "TJ", "TT"],
    "dev_composition": ["CC", "IJ", "JT", "TI"],
    "test_composition": ["CI", "IT", "JJ", "TC"],
}


# ---------------------------------------------------------------------------
# Fixtures: one real shared catalogue / report across the module.
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def catalogue() -> dict:
    return mcs.build_motif_split_catalogue()


@pytest.fixture(scope="module")
def real_report() -> dict:
    return mcp.audit_motif_candidates()


# ---------------------------------------------------------------------------
# JSON <-> object reconstruction helpers (independent oracle).
# ---------------------------------------------------------------------------
def _atom(pred: str, x: str, y: str) -> Atom:
    return Atom(pred, (x, y))


def _fact(pred: str, x: str, y: str) -> Clause:
    return Clause((), _atom(pred, x, y))


def _copy_clause(src: str, dst: str) -> Clause:
    return Clause((_atom(src, "?x", "?y"),), _atom(dst, "?x", "?y"))


def _inv_clause(src: str, dst: str) -> Clause:
    return Clause((_atom(src, "?x", "?y"),), _atom(dst, "?y", "?x"))


def _join_clause(src: str, side: str, dst: str) -> Clause:
    return Clause(
        (_atom(src, "?x", "?y"), _atom(side, "?y", "?z")),
        _atom(dst, "?x", "?z"),
    )


def _inter_clause(src: str, side: str, dst: str) -> Clause:
    return Clause(
        (_atom(src, "?x", "?y"), _atom(side, "?x", "?y")),
        _atom(dst, "?x", "?y"),
    )


def _from_json_atom(obj) -> Atom:
    return Atom(obj["pred"], tuple(obj["args"]))


def _from_json_clause(obj) -> Clause:
    return Clause(
        tuple(_from_json_atom(a) for a in obj["body"]),
        _from_json_atom(obj["head"]),
    )


def _from_json_step(obj) -> ProofStep:
    return ProofStep(obj["clause_index"], tuple(obj["premise_steps"]),
                     _from_json_atom(obj["conclusion"]))


def _reconstruct_row(row) -> tuple:
    clauses = tuple(_from_json_clause(c) for c in row["clauses"])
    query = _from_json_atom(row["query"])
    proof = tuple(_from_json_step(s) for s in row["proof"])
    return clauses, query, proof


def _key_to_json(key) -> object:
    if isinstance(key, tuple):
        return [_key_to_json(x) for x in key]
    return key


def _key_to_tuple(obj) -> object:
    if isinstance(obj, list):
        return tuple(_key_to_tuple(x) for x in obj)
    return obj


# ---------------------------------------------------------------------------
# Hand-written anchor witnesses (independent oracles).
# ---------------------------------------------------------------------------
def _base_step() -> ProofStep:
    return ProofStep(0, (), _atom("p0", "e0", "e1"))


_W_CC = (
    (_fact("p0", "e0", "e1"), _copy_clause("p0", "p1"), _copy_clause("p1", "p2")),
    _atom("p2", "e0", "e1"),
    (_base_step(),
     ProofStep(1, (0,), _atom("p1", "e0", "e1")),
     ProofStep(2, (1,), _atom("p2", "e0", "e1"))),
)

_W_CCC = (
    (_fact("p0", "e0", "e1"), _copy_clause("p0", "p1"),
     _copy_clause("p1", "p2"), _copy_clause("p2", "p3")),
    _atom("p3", "e0", "e1"),
    (_base_step(),
     ProofStep(1, (0,), _atom("p1", "e0", "e1")),
     ProofStep(2, (1,), _atom("p2", "e0", "e1")),
     ProofStep(3, (2,), _atom("p3", "e0", "e1"))),
)

_W_CJ = (
    (_fact("p0", "e0", "e1"), _copy_clause("p0", "p1"),
     _fact("s2", "e1", "e3"), _join_clause("p1", "s2", "p2")),
    _atom("p2", "e0", "e3"),
    (_base_step(),
     ProofStep(1, (0,), _atom("p1", "e0", "e1")),
     ProofStep(2, (), _atom("s2", "e1", "e3")),
     ProofStep(3, (1, 2), _atom("p2", "e0", "e3"))),
)

_W_CJC = (
    _W_CJ[0] + (_copy_clause("p2", "p3"),),
    _atom("p3", "e0", "e3"),
    _W_CJ[2] + (ProofStep(4, (3,), _atom("p3", "e0", "e3")),),
)

_W_CI = (
    (_fact("p0", "e0", "e1"), _copy_clause("p0", "p1"), _inv_clause("p1", "p2")),
    _atom("p2", "e1", "e0"),
    (_base_step(),
     ProofStep(1, (0,), _atom("p1", "e0", "e1")),
     ProofStep(2, (1,), _atom("p2", "e1", "e0"))),
)

_W_CIC = (
    _W_CI[0] + (_copy_clause("p2", "p3"),),
    _atom("p3", "e1", "e0"),
    _W_CI[2] + (ProofStep(3, (2,), _atom("p3", "e1", "e0")),),
)

ANCHORS = {
    "CC": _W_CC,
    "CCC": _W_CCC,
    "CJ": _W_CJ,
    "CJC": _W_CJC,
    "CI": _W_CI,
    "CIC": _W_CIC,
}


def _measured(clauses, query, proof):
    return (
        canonical_motif_key(
            clauses, query, proof,
            max_steps=_MAX_PROOF_STEPS, max_orientations=_MAX_ORIENTATIONS,
        ),
        count_canonical_proofs(
            clauses, query,
            max_fact_checks=_MAX_FACT_CHECKS, max_derivations=_MAX_DERIVATIONS,
            max_proof_steps=_MAX_PROOF_STEPS,
        ),
        minimum_proof_depth(
            clauses, query,
            max_fact_checks=_MAX_FACT_CHECKS, max_derivations=_MAX_DERIVATIONS,
        ),
    )


def _step_json(step) -> dict:
    return {"clause_index": step["clause_index"],
            "premise_steps": step["premise_steps"],
            "conclusion": step["conclusion"]}


# ---------------------------------------------------------------------------
# Fixed-directory, split, bucket, matrix, and summary literals.
# ---------------------------------------------------------------------------
class TestFixedDirectoryAndSplits:
    def test_eighty_rows_fixed_order(self, catalogue):
        rows = catalogue["candidates"]
        assert len(rows) == 80
        assert [r["id"] for r in rows] == list(_ALL_IDS)
        assert rows[0]["id"] == "CC"
        assert rows[-1]["id"] == "TTT"

    def test_each_candidate_split_literal(self, catalogue):
        expected_split = ({w: "train" for w in _TRAIN_IDS}
                          | {w: "dev_composition" for w in _DEV_IDS}
                          | {w: "test_composition" for w in _TEST_IDS})
        rows = catalogue["candidates"]
        for r in rows:
            assert r["split"] == expected_split[r["id"]], r["id"]
        assert {r["split"] for r in rows} == \
            {"train", "dev_composition", "test_composition"}

    def test_train_row_literal(self, catalogue):
        s = catalogue["splits"][0]
        assert s["name"] == "train"
        assert s["root_ids"] == _EXPECTED_ROOT_IDS["train"]
        assert s["candidate_ids"] == _TRAIN_IDS
        assert s["candidate_count"] == 40
        assert s["distinct_motif_count"] == 40
        assert s["buckets"] == _TRAIN_BUCKETS

    def test_dev_row_literal(self, catalogue):
        s = catalogue["splits"][1]
        assert s["name"] == "dev_composition"
        assert s["root_ids"] == _EXPECTED_ROOT_IDS["dev_composition"]
        assert s["candidate_ids"] == _DEV_IDS
        assert s["candidate_count"] == 20
        assert s["distinct_motif_count"] == 20
        assert s["buckets"] == _DEV_BUCKETS

    def test_test_row_literal(self, catalogue):
        s = catalogue["splits"][2]
        assert s["name"] == "test_composition"
        assert s["root_ids"] == _EXPECTED_ROOT_IDS["test_composition"]
        assert s["candidate_ids"] == _TEST_IDS
        assert s["candidate_count"] == 20
        assert s["distinct_motif_count"] == 20
        assert s["buckets"] == _TEST_BUCKETS

    def test_splits_fixed_order(self, catalogue):
        assert [s["name"] for s in catalogue["splits"]] == \
            ["train", "dev_composition", "test_composition"]

    def test_containment_matrix_literal(self, catalogue):
        assert catalogue["containment_matrix"] == _EXPECTED_MATRIX
        # both directions explicitly zero for every cross pair
        for c in catalogue["containment_matrix"]:
            if c["source_split"] != c["target_split"]:
                assert c["edge_count"] == 0, c
        assert len(catalogue["containment_matrix"]) == 9

    def test_summary_literal(self, catalogue):
        assert catalogue["summary"] == _EXPECTED_SUMMARY

    def test_top_level_constants_and_budgets(self, catalogue):
        assert catalogue["schema_version"] == _TOP_CONSTANTS["schema_version"]
        assert catalogue["split_protocol"] == _TOP_CONSTANTS["split_protocol"]
        assert catalogue["research_protocol"] == _TOP_CONSTANTS["research_protocol"]
        assert catalogue["candidate_family"] == _TOP_CONSTANTS["candidate_family"]
        assert catalogue["matching"] == _TOP_CONSTANTS["matching"]
        assert catalogue["budgets"] == _EXPECTED_BUDGETS
        assert set(catalogue) == set(_TOP_CONSTANTS) | {
            "budgets", "candidates", "splits",
            "containment_matrix", "summary"}


# ---------------------------------------------------------------------------
# Witness / measurement preservation.
# ---------------------------------------------------------------------------
class TestWitnessAndMeasurementPreserved:
    def test_rows_preserve_t0019_fields(self, catalogue, real_report):
        """The 80 catalogue rows are the 80 T0019 rows plus a split field:
        every field is value-identical, in the same order."""
        assert len(catalogue["candidates"]) == len(real_report["candidates"])
        for cat_row, rep_row in zip(catalogue["candidates"],
                                    real_report["candidates"]):
            for field in ("id", "clauses", "query", "proof",
                          "motif_key", "minimum_depth",
                          "canonical_proof_count", "proof_steps",
                          "contained_ids"):
                assert cat_row[field] == rep_row[field], field
            assert set(cat_row) == set(rep_row) | {"split"}
            assert isinstance(cat_row["split"], str)

    def test_full_witness_reconstruct_and_verify(self, catalogue):
        for row in catalogue["candidates"]:
            clauses, query, proof = _reconstruct_row(row)
            assert verify_proof(clauses, query, proof), row["id"]
            assert proof[-1].conclusion == query
            assert len(proof) == row["proof_steps"], row["id"]

    def test_anchor_witnesses_match(self, catalogue):
        rows = {r["id"]: r for r in catalogue["candidates"]}
        for word, (clauses, query, proof) in ANCHORS.items():
            assert verify_proof(clauses, query, proof), word
            assert proof[-1].conclusion == query
            row = rows[word]
            rc, rq, rp = _reconstruct_row(row)
            assert clauses == rc, word
            assert query == rq, word
            assert proof == rp, word
            key, cnt, depth = _measured(clauses, query, proof)
            assert row["motif_key"] == _key_to_json(key), word
            assert row["canonical_proof_count"] == cnt, word
            assert row["minimum_depth"] == depth, word
            assert row["proof_steps"] == len(proof), word

    def test_cjc_train_anchor_containment(self, catalogue):
        rows = {r["id"]: r for r in catalogue["candidates"]}
        assert rows["CJ"]["split"] == "train"
        assert rows["CJC"]["split"] == "train"
        # full contained list, in order; contains the prefix, not the
        # directionally-different JC.
        assert rows["CJC"]["contained_ids"] == ["CJ", "CJC"]
        assert "JC" not in rows["CJC"]["contained_ids"]
        # complete (non-empty) full keys, not just counts.
        assert rows["CJ"]["motif_key"]
        assert rows["CJC"]["motif_key"] != rows["CJ"]["motif_key"]

    def test_ccc_dev_anchor(self, catalogue):
        rows = {r["id"]: r for r in catalogue["candidates"]}
        assert rows["CC"]["split"] == "dev_composition"
        assert rows["CCC"]["split"] == "dev_composition"
        assert rows["CCC"]["contained_ids"] == ["CC", "CCC"]

    def test_cic_test_anchor(self, catalogue):
        rows = {r["id"]: r for r in catalogue["candidates"]}
        assert rows["CI"]["split"] == "test_composition"
        assert rows["CIC"]["split"] == "test_composition"
        assert rows["CIC"]["contained_ids"] == ["CI", "CIC"]


# ---------------------------------------------------------------------------
# Single dependency call, isolation, and no original-object pollution.
# ---------------------------------------------------------------------------
class TestDependencySingleCall:
    def test_audited_once_with_no_args(self):
        base = mcp.audit_motif_candidates()
        old = getattr(mcs, "audit_motif_candidates")
        seen = []

        def spy(*a, **kw):
            seen.append((len(a), len(kw)))
            return base

        try:
            mcs.audit_motif_candidates = spy
            mcs.build_motif_split_catalogue()
        finally:
            mcs.audit_motif_candidates = old
        assert seen == [(0, 0)]


class TestIsolationAndContamination:
    def test_no_stdout_on_call(self):
        buf = io.StringIO()
        old = sys.stdout
        sys.stdout = buf
        try:
            mcs.build_motif_split_catalogue()
        finally:
            sys.stdout = old
        assert buf.getvalue() == ""

    def test_dependency_report_not_shared(self):
        base = mcp.audit_motif_candidates()
        row0 = base["candidates"][0]
        snapshot = json.loads(json.dumps(base, ensure_ascii=False))
        old = getattr(mcs, "audit_motif_candidates")
        seen = {"rep": None}

        def spy():
            seen["rep"] = base
            return base

        try:
            mcs.audit_motif_candidates = spy
            cat = mcs.build_motif_split_catalogue()
        finally:
            mcs.audit_motif_candidates = old
        assert seen["rep"] is base
        # top-level row, its nested containers, and its key are all new
        # objects, not the dependency report's.
        assert cat["candidates"][0] is not row0
        assert cat["candidates"][0]["contained_ids"] is not row0["contained_ids"]
        assert cat["candidates"][0]["clauses"] is not row0["clauses"]
        assert cat["candidates"][0]["clauses"][0] is not row0["clauses"][0]
        assert cat["candidates"][0]["motif_key"] is not row0["motif_key"]
        # mutating the catalogue (including nested containers) never mutates
        # the live dependency report.
        cat["candidates"][0]["contained_ids"].append("xx")
        cat["candidates"][0]["clauses"][0]["body"].append(_atom("z", "a", "b"))
        cat["candidates"][0]["motif_key"].append(99)
        assert json.loads(json.dumps(base, ensure_ascii=False)) == snapshot
        cat2 = mcs.build_motif_split_catalogue()
        assert cat2["summary"] == _EXPECTED_SUMMARY

    def test_import_resolves_to_worktree_split(self):
        src = Path(__file__).resolve().parents[1] / "src"
        env = _child_env()
        # Shared header checks kmesh.__file__ and the target module's spec
        # origin / __file__ against this worktree.
        script = _child_script(src, "")
        out = subprocess.run([sys.executable, "-I", "-B", "-c", script],
                             env=env, capture_output=True, text=True, timeout=120)
        assert out.returncode == 0, out.stderr

    def test_import_forbidden_roots(self):
        src = Path(__file__).resolve().parents[1] / "src"
        env = _child_env()
        # Shared header installs the forbidden-import blocker and asserts the
        # kmesh root plus the target module's spec origin / __file__ against
        # this worktree.
        script = _child_script(src, "")
        out = subprocess.run([sys.executable, "-I", "-B", "-c", script],
                             env=env, capture_output=True, text=True, timeout=120)
        assert out.returncode == 0, out.stderr



# ---------------------------------------------------------------------------
# Rejection tests (mutate a copy of the real report; expect RuntimeError).
# ---------------------------------------------------------------------------
def _expect_reject(mutate):
    """Run the build with a mutated copy of the real audit report; require
    ``RuntimeError(_ERROR)`` (no partial JSON, no retry)."""
    base = mcp.audit_motif_candidates()
    mutated = copy.deepcopy(base)
    mutate(mutated)
    old = getattr(mcs, "audit_motif_candidates")
    buf = io.StringIO()
    old_stdout = sys.stdout
    sys.stdout = buf
    try:
        mcs.audit_motif_candidates = lambda: mutated
        with pytest.raises(RuntimeError,
                           match="motif_split candidate audit violates motif_split_v1"):
            mcs.build_motif_split_catalogue()
    finally:
        sys.stdout = old_stdout
        mcs.audit_motif_candidates = old
    assert buf.getvalue() == ""


def _row_by_id(rep, word):
    return next(r for r in rep["candidates"] if r["id"] == word)


class TestCrossSplitRejection:
    # Fixtures are otherwise valid (self present, unique, in global directory
    # order); only the cross-split member violates the rule, so the rejection
    # must come from the cross-split check itself, not from the order check.
    def test_train_cjc_containing_dev_cc_rejected(self):
        def mutate(r):
            row = _row_by_id(r, "CJC")
            row["contained_ids"] = ["CC", "CJ", "CJC"]
        _expect_reject(mutate)

    def test_dev_ccc_containing_test_ci_rejected(self):
        def mutate(r):
            row = _row_by_id(r, "CCC")
            row["contained_ids"] = ["CC", "CI", "CCC"]
        _expect_reject(mutate)

    def test_test_cic_containing_dev_cc_rejected(self):
        def mutate(r):
            row = _row_by_id(r, "CIC")
            row["contained_ids"] = ["CC", "CI", "CIC"]
        _expect_reject(mutate)


class TestStructuralRejection:
    def test_duplicate_complete_key_rejected(self):
        def mutate(r):
            _row_by_id(r, "CJ")["motif_key"] = \
                copy.deepcopy(_row_by_id(r, "IC")["motif_key"])
        _expect_reject(mutate)

    def test_cross_split_duplicate_complete_key_rejected(self):
        def mutate(r):
            _row_by_id(r, "CJ")["motif_key"] = \
                copy.deepcopy(_row_by_id(r, "CC")["motif_key"])
        _expect_reject(mutate)

    def test_duplicate_id_rejected(self):
        def mutate(r):
            r["candidates"][1].update({"id": "CC"})
        _expect_reject(mutate)

    def test_missing_id_rejected(self):
        def mutate(r):
            r["candidates"].pop()
        _expect_reject(mutate)

    def test_unknown_id_rejected(self):
        def mutate(r):
            r["candidates"][0].update({"id": "ZZ"})
        _expect_reject(mutate)

    def test_reordering_rejected(self):
        def mutate(r):
            rows = r["candidates"]
            rows[0], rows[1] = rows[1], rows[0]
        _expect_reject(mutate)

    def test_non_unique_proof_count_rejected(self):
        def mutate(r):
            _row_by_id(r, "CJ").update({"canonical_proof_count": 2})
        _expect_reject(mutate)

    def test_non_int_proof_count_rejected(self):
        for bad in (True, 1.0, "1", None):
            def mutate(r, bad=bad):
                _row_by_id(r, "CJ").update({"canonical_proof_count": bad})
            _expect_reject(mutate)

    def test_depth_not_word_length_rejected(self):
        def mutate(r):
            _row_by_id(r, "CC").update({"minimum_depth": 3})
        _expect_reject(mutate)

    def test_steps_not_proof_len_rejected(self):
        def mutate(r):
            _row_by_id(r, "CC").update({"proof_steps": 4})
        _expect_reject(mutate)

    def test_bad_bucket_rejected(self):
        """Shift a 2-letter row to a neighbouring in-table (depth, steps)
        bucket by lengthening its proof (and its proof_steps); the per-set
        (depth, steps) counts then disagree with the protocol table and must
        be rejected.  (The real (2,3)/(2,4) rows already fill those table
        cells, so moving a row out breaks the literal counts.)"""
        def mutate(r):
            row = _row_by_id(r, "CC")
            # keep proof_steps consistent with proof length, but move the row
            # into an out-of-table bucket by giving it a 4th step.
            row["proof"] = row["proof"] + [_step_json({
                "clause_index": 3,
                "premise_steps": (2,),
                "conclusion": {"pred": "p3", "args": ["e0", "e1"]},
            })]
            row["proof_steps"] = 4
            row["minimum_depth"] = 2
        _expect_reject(mutate)


# ---------------------------------------------------------------------------
# Exception propagation (original instance, pre-call message, no retry).
# ---------------------------------------------------------------------------
class TestExceptionPropagation:
    def test_upstream_exception_propagates(self):
        exc = LogicValidationError("split_upstream_fail")
        cause = RuntimeError("split_cause_marker")
        ctx = LogicValidationError("split_context_marker")
        exc.__cause__ = cause
        exc.__context__ = ctx
        msg_before = str(exc)
        seen = {"n": 0}

        def fake(*a, **kw):
            seen["n"] += 1
            raise exc

        old = getattr(mcs, "audit_motif_candidates")
        buf = io.StringIO()
        old_stdout = sys.stdout
        sys.stdout = buf
        try:
            mcs.audit_motif_candidates = fake
            with pytest.raises(LogicValidationError) as excinfo:
                mcs.build_motif_split_catalogue()
        finally:
            sys.stdout = old_stdout
            mcs.audit_motif_candidates = old
        assert seen["n"] == 1, seen
        assert excinfo.value is exc
        assert str(excinfo.value) == msg_before
        assert excinfo.value.__cause__ is cause
        assert excinfo.value.__context__ is ctx
        assert buf.getvalue() == ""


# ---------------------------------------------------------------------------
# Isolated dependency stand-in: pass-through and independence of counts.
# ---------------------------------------------------------------------------
class TestKeySentinelPassThrough:
    def test_sentinel_keys_pass_through(self):
        def standin():
            base = mcp.audit_motif_candidates()
            rep = copy.deepcopy(base)
            for i, row in enumerate(rep["candidates"]):
                row["motif_key"] = ("sentinel_v1", i)
            return rep

        old = getattr(mcs, "audit_motif_candidates")
        try:
            mcs.audit_motif_candidates = standin
            cat = mcs.build_motif_split_catalogue()
        finally:
            mcs.audit_motif_candidates = old
        assert cat["summary"]["distinct_motif_count"] == 80
        for i, row in enumerate(cat["candidates"]):
            assert row["motif_key"] == ("sentinel_v1", i), row["id"]

    def test_unrelated_upstream_summary_not_oracle(self):
        """The catalogue recomputes its own counts from the rows; the
        upstream summary/buckets are not the source of the output."""
        def standin():
            base = mcp.audit_motif_candidates()
            rep = copy.deepcopy(base)
            rep["summary"] = {"candidate_count": 0}
            rep["buckets"] = []
            return rep

        old = getattr(mcs, "audit_motif_candidates")
        try:
            mcs.audit_motif_candidates = standin
            cat = mcs.build_motif_split_catalogue()
        finally:
            mcs.audit_motif_candidates = old
        assert cat["summary"] == _EXPECTED_SUMMARY
        assert [s["candidate_count"] for s in cat["splits"]] == [40, 20, 20]

    def test_synthetic_same_split_containment_recomputed(self):
        """A synthetic report whose only change is a same-split contained
        list shrink (CJC -> self-only) must yield a recomputed summary and
        matrix: 143/63 edges, train diagonal 71, all other cells unchanged.
        A mutant that hardcodes containment_edges=144 and the 72/36/36
        matrix literals fails here."""
        def standin():
            base = mcp.audit_motif_candidates()
            rep = copy.deepcopy(base)
            _row_by_id(rep, "CJC")["contained_ids"] = ["CJC"]
            return rep

        old = getattr(mcs, "audit_motif_candidates")
        try:
            mcs.audit_motif_candidates = standin
            cat = mcs.build_motif_split_catalogue()
        finally:
            mcs.audit_motif_candidates = old
        assert next(r["contained_ids"]
                    for r in cat["candidates"] if r["id"] == "CJC") == ["CJC"]
        assert cat["summary"] == {
            "candidate_count": 80,
            "distinct_motif_count": 80,
            "containment_edges": 143,
            "proper_containment_edges": 63,
            "cross_split_edges": 0,
        }
        cells = {(c["source_split"], c["target_split"]): c["edge_count"]
                 for c in cat["containment_matrix"]}
        assert cells[("train", "train")] == 71
        assert cells[("dev_composition", "dev_composition")] == 36
        assert cells[("test_composition", "test_composition")] == 36
        for pair, n in cells.items():
            if pair[0] != pair[1]:
                assert n == 0, (pair, n)


# ---------------------------------------------------------------------------
# Subprocess determinism and import isolation (modeled on T0019).
# ---------------------------------------------------------------------------
def _child_env():
    env = dict(os.environ)
    env.pop("PYTHONPATH", None)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env["CUDA_VISIBLE_DEVICES"] = ""
    env["PYTEST_DISABLE_PLUGIN_AUTOLOAD"] = "1"
    return env


def _child_script(src, body, tail=None, footer_asserts=True):
    """Assemble the -I -B child: worktree src first, resolved product path,
    a forbidden-import blocker, and a sys.modules scan.  The shared header
    always asserts that both the kmesh package root and the target module
    realpath to this worktree, so every child (including the failure-path
    script) checks them before the body runs."""
    src_str = str(src)
    split_real = str(src / "kmesh" / "logic" / "motif_split.py")
    types_real = str(src / "kmesh" / "logic" / "types.py")
    kmesh_real = str(src / "kmesh" / "__init__.py")
    header = f"""import sys, os, importlib
sys.path.insert(0, {src_str!r})
import kmesh
assert os.path.realpath(kmesh.__file__) == {kmesh_real!r}, kmesh.__file__
import kmesh.logic.types as _kt
assert os.path.realpath(_kt.__file__) == {types_real!r}, _kt.__file__
FORBIDDEN = ('torch', 'yaml', 'kmesh.logic.engine',
            'kmesh.logic.reference_engine')
class BlockFinder:
    def find_spec(self, fullname, path=None, target=None):
        for f in FORBIDDEN:
            if fullname == f or fullname.startswith(f + '.'):
                raise ImportError('forbidden-import: ' + fullname)
        return None
sys.meta_path.insert(0, BlockFinder())
def _assert_blocked(name):
    try:
        importlib.import_module(name)
    except ImportError as e:
        assert 'forbidden-import: ' in str(e), (name, e)
        return
    raise AssertionError('forbidden ' + name + ' imported despite blocker')
for name in FORBIDDEN + ('torch.sub', 'kmesh.logic.engine.sub',
                         'kmesh.logic.reference_engine.sub'):
    _assert_blocked(name)
import kmesh.logic.motif_split as _pm
assert os.path.realpath(_pm.__file__) == {split_real!r}, _pm.__file__
assert _pm.__spec__ is not None, _pm.__spec__
assert os.path.realpath(_pm.__spec__.origin) == {split_real!r}, _pm.__spec__.origin
def _bad():
    return [n for n in sys.modules if any(
        n == f or n.startswith(f + '.') for f in FORBIDDEN)]
before = _bad()
assert before == [], before
"""
    if footer_asserts:
        footer = (
            "assert _bad() == before, _bad()\n"
            "assert isinstance(sys.meta_path[0], BlockFinder)\n"
        )
        if tail:
            footer += f"print('{tail}')\n"
    else:
        footer = ""
    return header + body + footer


class TestDeterminismAndIsolation:
    def test_repeated_calls_independent(self):
        base_snapshot = json.loads(
            json.dumps(mcs.build_motif_split_catalogue(), ensure_ascii=False))
        a = mcs.build_motif_split_catalogue()
        b = mcs.build_motif_split_catalogue()
        assert a == base_snapshot
        assert b == base_snapshot
        assert a is not b
        # mutate one returned catalogue (including nested containers); a fresh
        # build must be unaffected (independent copies, not a shared report).
        a["candidates"][0]["contained_ids"].append("MUT")
        a["candidates"][0]["clauses"][0]["body"].append(_atom("z", "a", "b"))
        a["candidates"][0]["motif_key"].append(999)
        a["summary"]["candidate_count"] = 0
        c = mcs.build_motif_split_catalogue()
        d = mcs.build_motif_split_catalogue()
        assert c == base_snapshot
        assert d == base_snapshot

    def test_subprocess_byte_identical_and_valid_json(self):
        repo_root = Path(__file__).resolve().parents[1]
        src = repo_root / "src"
        split_real = str(src / "kmesh" / "logic" / "motif_split.py")
        env = _child_env()
        script = _child_script(
            src,
            "import runpy\n"
            "import warnings\n"
            "with warnings.catch_warnings():\n"
            "    warnings.filterwarnings('ignore', message=\".+' found in sys\\\\.modules after import of package\")\n"
            "    ns = runpy.run_module('kmesh.logic.motif_split', run_name='__main__')\n"
            "assert ns['__name__'] == '__main__', ns['__name__']\n"
            "spec = ns['__spec__']\n"
            "assert spec is not None, spec\n"
            f"assert os.path.realpath(spec.origin) == {split_real!r}, spec.origin\n",
            tail=None,
        )
        pyc_before = {str(p) for p in src.rglob("*.pyc")}
        out1 = subprocess.run([sys.executable, "-I", "-B", "-c", script],
                              env=env, capture_output=True, text=False,
                              timeout=600)
        out2 = subprocess.run([sys.executable, "-I", "-B", "-c", script],
                              env=env, capture_output=True, text=False,
                              timeout=600)
        assert out1.returncode == 0, out1.stderr
        assert out2.returncode == 0, out2.stderr
        assert out1.stdout == out2.stdout
        assert out1.stderr == b""
        assert out1.stdout.endswith(b"\n")
        cli = json.loads(out1.stdout.decode("utf-8"))
        assert cli == mcs.build_motif_split_catalogue()
        assert cli["schema_version"] == "motif_split_catalogue_v1"
        assert cli["summary"]["candidate_count"] == 80
        pyc_after = {str(p) for p in src.rglob("*.pyc")}
        assert pyc_after == pyc_before, \
            f"new pyc: {sorted(pyc_after - pyc_before)}"

    def test_isolated_process_build_no_forbidden_modules(self):
        repo_root = Path(__file__).resolve().parents[1]
        src = repo_root / "src"
        env = _child_env()
        script = _child_script(
            src,
            "import kmesh.logic.motif_split as m\n"
            "cat = m.build_motif_split_catalogue()\n"
            "assert cat['summary']['candidate_count'] == 80\n"
            "assert cat['summary']['cross_split_edges'] == 0\n",
            tail="OK_ISOLATION",
        )
        out = subprocess.run([sys.executable, "-I", "-B", "-c", script],
                             env=env, capture_output=True, text=True,
                             timeout=600)
        assert out.returncode == 0, out.stderr
        assert "OK_ISOLATION" in out.stdout

    def test_cli_failure_writes_no_partial_json(self):
        repo_root = Path(__file__).resolve().parents[1]
        src = repo_root / "src"
        env = _child_env()
        script = _child_script(
            src,
            "import kmesh.logic.motif_split as m\n"
            "from kmesh.logic.types import LogicValidationError\n"
            "def fail():\n"
            "    raise LogicValidationError('split_cli_fail_sentinel')\n"
            "m.audit_motif_candidates = fail\n"
            "m._main()\n",
            footer_asserts=False,
        )
        out = subprocess.run([sys.executable, "-I", "-B", "-c", script],
                             env=env, capture_output=True, text=True,
                             timeout=600)
        assert out.returncode != 0
        assert "split_cli_fail_sentinel" in out.stderr
        assert "Traceback" in out.stderr
        assert out.stdout.strip() == ""
